import type { Metadata } from "next";
import "./globals.css";

import { Kanit } from "next/font/google";
const kanit = Kanit({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

import "@mantine/core/styles.layer.css";
import "mantine-datatable/styles.layer.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import {
  DirectionProvider,
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";
import { theme } from "./theme";

import TopLoader from "@/components/ui/loading/toploader";
import { DateProvider } from "@/components/provider/date-provider";

export const metadata: Metadata = {
  title: "MIS แผน",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={kanit.className}
      {...mantineHtmlProps}
      suppressHydrationWarning
    >
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body suppressHydrationWarning>
        <DirectionProvider initialDirection="ltr" detectDirection={false}>
          <MantineProvider theme={theme}>
            <DateProvider>
              <Notifications position="bottom-right" zIndex={1000} />
              <ModalsProvider>
                <TopLoader />
                {children}
              </ModalsProvider>
            </DateProvider>
          </MantineProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
